#!/bin/bash
#
#SBATCH --output=/home/USERNAME/slurm/out/%j.%N.stdout
#SBATCH --error=/home/USERNAME/slurm/out/%j.%N.stderr
#SBATCH --partition=general
#SBATCH --job-name=cmap
#SBATCH --time=12:00:00
#SBATCH --mem=64GB
#SBATCH --cpus-per-task=8
#SBATCH --tasks-per-node=1
#SBATCH --gres=gpu:2

export PATH="~/miniconda/bin:$PATH"

# conda activate cmap
source ~/miniconda3/bin/activate cmap

cd ~/cmap
wandb agent cmap-2024/cmap/z1wwd8na --count 5
