import os
from typing import Any, DefaultDict

import matplotlib.pyplot as plt
import numpy as np


def plot_training_sample(sample: DefaultDict[str, Any], save_root: str):
    """
    Plots a sample from the training dataset and saves to provided directory.

    Parameters
    ----------
    sample : defaultdict
        A sample from the training dataset, generated by DataLoader

    save_root : str
        The directory to save the plot to.
    """
    # extract the mask and image from the sample
    mask = sample["mask"].numpy().astype(np.uint8).squeeze()
    image = sample["image"].numpy().astype(np.uint8).squeeze()

    _, ax = plt.subplots(1, 2, figsize=(10, 5))

    # plot the mask
    ax[0].imshow(mask[1], extent=sample["bbox"][0][:4])
    ax[0].set_title("Mask")
    ax[0].axis("off")

    # plot the image
    ax[1].imshow(image[1], extent=sample["bbox"][0][:4], cmap="gray")
    ax[1].set_title("NAIP Chip")
    ax[1].axis("off")

    # TODO: change this to a more descriptive name
    fname = os.path.join(save_root, "sample.png")
    plt.savefig(fname)
