program: train.py
method: bayes
metric:
  goal: maximize
  name: average_test_jaccard_index

parameters:
  batch_size:
    values: [8, 16, 32]
  learning_rate:
    values: [1e-4, 1e-5, 1e-6]
  patch_size:
    values: [256, 512, 768]
  color_brightness:
    values: [0.2, 0.3, 0.4, 0.5]
  gaussian_blur_sigma:
    values:
      - [0.1, 0.2]
      - [0.3, 0.4]
      - [0.5, 0.6]
  gaussian_blur_kernel:
    values:
      - [3,3]
      - [5,5]
      - [7,7]
command:
- python
- train.py
- configs.config
- --tune 
- --num_trials
- 5


